spring:
  application:
    name: briscula

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/briscula
    username: postgres
    password: 123

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration-dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.web: DEBUG
#    org.springframework.web.socket: DEBUG

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket.server.support: DEBUG
