package com.example.web.model.enums;

public enum ServerToClientMessageType {
  GAME_STARTED,
  SENT_INITIAL_CARDS,
  CARDS_STATE_UPDATE,
  CHOOSE_CARD,
  REMOVE_CARD,
  REMOVE_MAIN_CARD,
  PLAYER_LOST,
  PLAYER_WON,
  NO_WINNER,
  SENT_MAIN_CARD,
  RECEIVED_THROWN_CARD,
  SENT_COLLEAGUES_CARDS,
  WAIT_FOR_NEXT_MATCH
}
